tests: Fix building against modern GTest
Fixes being unable to locate GMock (GTest) with gtest v1.12.1 as tested
on Void Linux:

  CMake Warning at tests/CMakeLists.txt:1 (find_package):
    By not providing "FindGMock.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "GMock", but
    CMake did not find one.

    Could not find a package configuration file provided by "GMock" with any of
    the following names:

      GMockConfig.cmake
      gmock-config.cmake

    Add the installation prefix of "GMock" to CMAKE_PREFIX_PATH or set
    "GMock_DIR" to a directory containing one of the above files.  If "GMock"
    provides a separate development package or SDK, be sure it has been
    installed.

Also mark the library as REQUIRED since without it found attempting to
build tests just fails at link-time with various errors such as:

  /usr/bin/ld: gtest-menuitems.cpp:(.text+0x14d): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'